services:
  mongodb:
    image: mongo:latest
    container_name: rag_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  selenium:
    image: selenium/standalone-chrome:118.0
    container_name: selenium
    shm_size: '2gb'
    environment:
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_SESSION_TIMEOUT=300
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC port for debugging
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:4444/wd/hub/status" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s


  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag_scraper
    restart: unless-stopped
    environment:
      - SERVICE=scraper
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/?authSource=admin
      - SELENIUM_REMOTE_URL=http://selenium:4444/wd/hub
    depends_on:
      selenium:
        condition: service_healthy

  rag_updater:
    build: .
    container_name: rag_updater
    restart: unless-stopped
    environment:
      - SERVICE=rag
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/
    volumes:
      - vectorstore_data:/app/data/vectorstore/chroma
    depends_on:
      - mongodb

  backend:
    build: .
    container_name: rag_backend
    restart: unless-stopped
    environment:
      - SERVICE=backend
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - VECTORSTORE_DIR=/app/data/vectorstore/chroma
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/
    volumes:
      - vectorstore_data:/app/data/vectorstore/chroma
    ports:
      - "8000:5000"
    depends_on:
      - mongodb

  frontend:
    build: .
    container_name: rag_frontend
    restart: unless-stopped
    environment:
      - SERVICE=frontend
      - FLASK_BACKEND_URL=http://backend:5000
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_started


volumes:
  articles_data:
  vectorstore_data:
  mongodb_data: